import { FeatureCard } from "types";

export const features: FeatureCard[] = [
  {
    title: "Upload PDF",
    description:
      "Upload your PDF as your assignment brief and Gluglu will extract the details for you.",
    icon: "page",
    href: "/",
  },
  {
    title: "Generate content",
    description:
      "Based on the provided brief, Gluglu will generate the content for you.",
    icon: "settings",
    href: "/",
  },
  {
    title: "Academic Sources",
    description: "Include academic sources provided by Gluglu in your project.",
    icon: "search",
    href: "/",
  },
  {
    title: "Edit content",
    description:
      "Edit the content generated by Gluglu to fit your project's needs.",
    href: "/",
  },
  {
    title: "Thought Process",
    description:
      "Ask, and Gluglu will show you the thought process behind the decisions made in generating the content.",
  },
  {
    title: "Download PDF",
    description: "Download the generated project as PDF.",
  },
];
